@startuml
title View 3 - Handler Component View \nE.g.: Helth Check API Usage

box "Controller"
participant "HealthCheck Controller" as hChekApiController
end box

box "Handler Component" #PerlWhite
participant "HealthCheck Handler" as hChekApiHndlr
end box

box "Repository" #BBCCFF
participant "HealthCheck Data Repo" as hChekApiDataRepo
participant "HealthCheck Service Repo" as hChekApiSvcRepo
end box

skinparam sequence {
    ActorFontName Arial
    ActorFontSize 11

    ParticipantFontName Arial
    ParticipantFontSize 11

    ArrowFontName Arial
    ArrowFontSize 11
}



@enduml