@startuml
title View 2 - Pipeline Component View \nE.g.: Health Check API Usage

participant Browser as bw

box "Pipeline Components" #D9EDB7
participant "AuthenticationFilter" as authApiFilter
participant "AuditIntercepter" as auditApiIntercepter
end box

box "Controller"
participant "HealthController" as hChekApiController
end box

skinparam sequence {
    ActorFontName Arial
    ActorFontSize 11

    ParticipantFontName Arial
    ParticipantFontSize 11

    ArrowFontName Arial
    ArrowFontSize 11
}

bw->authApiFilter: Receive request \n    - [...]Query \n    - [...]Command
activate bw
activate authApiFilter

authApiFilter->auditApiIntercepter: Handover request
destroy authApiFilter
activate auditApiIntercepter

auditApiIntercepter->auditApiIntercepter: Audit request
auditApiIntercepter->hChekApiController: Handover request\n - HealthCheckQuery
destroy auditApiIntercepter
activate hChekApiController
hChekApiController->hChekApiController: Process the request

hChekApiController-->auditApiIntercepter: Return response\n - HealthCheckQueryResult
deactivate hChekApiController
activate auditApiIntercepter

auditApiIntercepter->auditApiIntercepter: Audit response

auditApiIntercepter-->bw: Return response \n-    [...]QueryResult \n-    [...]CommandResult
destroy auditApiIntercepter
deactivate bw
@enduml