@startuml
title View 3 - Handler Component View - E.g.: Helth Check API Usage

box "Service Layer" #LightBlue
participant "HealthCheck Controller" as hChekApiController

participant "HealthCheck Handler" as hChekApiHndlr
participant "HealthCheck Data Repo" as hChekApiDataRepo
participant "HealthCheck Service Repo" as hChekApiSvcRepo
end box

skinparam sequence {
    ActorFontName Arial
    ActorFontSize 11

    ParticipantFontName Arial
    ParticipantFontSize 11

    ArrowFontName Arial
    ArrowFontSize 11
}



@enduml