@startuml
title View 1 - Solution View \nE.g.: Helth Check API Usage

actor user
participant Browser as bw

box "Service Layer" #LightBlue
participant "System" as hChekApi
end box

skinparam sequence {
    ActorFontName Arial
    ActorFontSize 11

    ParticipantFontName Arial
    ParticipantFontSize 11

    ArrowFontName Arial
    ArrowFontSize 11
}

user->bw: Access the site
activate bw

bw->hChekApi: Send Request \n - HealthCheckQuery \n - URI = /api/v1/hchk
activate hChekApi
hChekApi-->bw:Receive Response \n - HealthCheckQueryResult \n --Content = "Ping with server Date & Time" \n --Status Code = 0
deactivate hChekApi
destroy hChekApi

bw-->user: Display Message
deactivate bw

@enduml